### ISSUE TITLE
Не работят записите на каналите

### ISSUE THREAD

**Issue by g79petova** [ByJohnie/plugin.video.mtelnow#13]
Изглежда има промяна в сайта , след което спряха да работят записите на каналите.

**Comment by m-stoev** [comment]
По-скоро бих казал, че проблема е в секцията ТВ Програма, реално ако от друго място си запишеш нещо се появява и работи в Моята секция.
Та като избереш ТВ Програма горе в дясно излиза надпис A1 TV GO error Check the log for more information.
Като проверя лога ето това излиза за приставката:

2021-10-05 20:31:41.398 T:4796     INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2021-10-05 20:31:41.494 T:4965     INFO <general>: initializing python engine.
2021-10-05 20:31:42.148 T:4965     INFO <general>: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.mtelnow/default.py): script successfully run
2021-10-05 20:31:42.386 T:4965     INFO <general>: Python interpreter stopped
2021-10-05 20:32:48.316 T:4805     INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-10-05 20:32:48.316 T:4805     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=AMLAUGESOUND,DEV=0"
2021-10-05 20:32:48.322 T:4805     INFO <general>: CAESinkALSA::Initialize - Opened device "hdmi:CARD=AMLAUGESOUND,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2021-10-05 20:32:48.322 T:4805     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2021-10-05 20:32:48.322 T:4805     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S16NE
2021-10-05 20:32:48.410 T:4975     INFO <general>: initializing python engine.
2021-10-05 20:32:48.749 T:4975    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'data'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.mtelnow/default.py", line 409, in <module>
                                                       indexChannelList()
                                                     File "/storage/.kodi/addons/plugin.video.mtelnow/default.py", line 170, in indexChannelList
                                                       for channel in res['data']['channelList']['channels']['edges']:
                                                   KeyError: 'data'
                                                   -->End of Python script error report<--
                                                   
2021-10-05 20:32:48.998 T:4975     INFO <general>: Python interpreter stopped
2021-10-05 20:32:49.013 T:4973    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.mtelnow/?device_id=1c06bcc3-aa42-5711-ba88-cde02ace417d&mode=indexChannelList&profile_id=8452&timeout=1633455912
2021-10-05 20:32:49.025 T:4796    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mtelnow/?device_id=1c06bcc3-aa42-5711-ba88-cde02ace417d&mode=indexChannelList&profile_id=8452&timeout=1633455912) failed
2021-10-05 20:32:49.041 T:4979     INFO <general>: initializing python engine.
2021-10-05 20:32:49.577 T:4979     INFO <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.mtelnow/default.py): script successfully run
2021-10-05 20:32:49.826 T:4979     INFO <general>: Python interpreter stopped

Надявам се това да помогне, защото това приложение е супер удобно.
Поздрави!

**Comment by lukavia** [comment]
Здравейте, мисля че оправих скоро подобен проблем в работната ми версия, която може да инсталирате от адрес: https://lukavia.github.io/lukav-kodi-repo/ 
Бихте ли проверили дали с нея продължавате да изпитвате този проблем?

**Comment by m-stoev** [comment]
Чудесна новина, ако не тази вечер утре ще пробвам и ще пиша!
Поздрави!

ПП - свалих и пробвах на Odroid N2+, първия път като цъкнах на ТВ Програма пак изкара същата грешка, втория път прочете и изведе листа, след това си избрах нещо по БТВ-то и тръгна без проблеми.
Лично аз ще си добавя репото в Кодито, да кача ли линк във форума на Коди или предпочиташ ти да го добавиш?
